// POST auth
POST http://localhost:9000/seller/auth

### Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json

{
    "store_id": "store_01JFF3P95PSW8S730S00653HVJ",
    "wallet_address": "0xc4968b973c6f346C8627f5935eE636Ea56764862"
}

#### Login Admin User
POST http://localhost:9000/admin/auth
Content-Type: application/json

{
  "email": "admin@medusa-test.com",
  "password": "supersecret"
}

### MOCK ORDERS
POST http://localhost:9000/admin/custom/mock-orders
Content-Type: application/json

{
  "count": 2,
  "date": "2024-12-04T10:00:00Z",
  "store_id": "store_01JEB9QTTBKJ0JJ8WCTXJCYGN4"
}


###
POST http://localhost:9000/seller/order/refund
Content-Type: application/json

{
  "order_id": "order_01JEAMPWRH6Y8ZND8B15NWSJAE",
  "amount": 6796,
  "reason": "return",
  "note": "this shit sucks, I hate it, give ma money back fool"
}


### Confirm REFUND ORDER
PUT http://localhost:9000/seller/order/refund
Content-Type: application/json

{
  "id": "ref_01JEBFA7QJQ5W9DYZH31Z5VFZQ"
}



###
// Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

{
  "store_id": "store_01JE8YPNX7QFSQF4T0RHR6V2BE",
  "page": 0,
  "ordersPerPage": 8,
  "sort": {
    "created_at": "ASC"
  },
  "filter": {
    "status": {
      "in": [
        "pending",
        "completed"
      ]
    },
    "fulfillment_status": {
      "eq": "not_fulfilled"
    },
    "payment_status": {
      "eq": "awaiting"
    }
  }

}

### Get Seller Order Details
GET http://localhost:9000/seller/order/detail?order_id=order_01JFHN02KH5F61X9786RVCSY63
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

### MODIFY ORDER STATUS && ADD NOTE?
PUT http://localhost:9000/seller/order/status
Content-Type: application/json

{
  "order_id": "order_01JCHZ33D14HBQ298MAQ6JC1D2",
  "status": "canceled",
  "note": "this guy just wasted our time, just return his money so he shuts up"

}

### Store Name
GET  http://localhost:9000/seller/store/name
Content-Type: application/json

{
  "wallet_address": "0xfb20a78fd35d20925af6f7379ab35fa6c41e9834"
}

### export csv
GET http://localhost:9000/seller/product/csv/export
Content-Type: application/json

{
  "store_id": "store_01JEVAP3K1YZV7HFRHZ6SFFR12"
}

### Get cancelled orders
GET  http://localhost:9000/seller/order/cancel-request
Content-Type: application/json

{
  "store_id": "store_01JEWRFN08KNC6S9M6NAYGDPBZ"
}

### delete product
DELETE http://localhost:9000/seller/product
Content-Type: application/json

{
  "product_id": "prod_01JFCJBKQCEW6EPP1CTPWCXT53"
}