// POST auth
POST http://localhost:9000/seller/auth

### Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json

{
    "store_id": "store_01JE8YPNX7QFSQF4T0RHR6V2BE",
    "wallet_address": "0xb975Bf5ca0b09E17834d0b5A526F8315F82986D4"
}

#### Login Admin User
POST http://localhost:9000/admin/auth
Content-Type: application/json

{
  "email": "admin@medusa-test.com",
  "password": "supersecret"
}

### MOCK ORDERS
POST http://localhost:9000/admin/custom/mock-orders
Content-Type: application/json

{
  "count": 2,
  "date": "2024-12-04T10:00:00Z",
  "store_id": "store_01JEB9QTTBKJ0JJ8WCTXJCYGN4"
}


###
// Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

{
  "store_id": "store_01JDVS0Z3RPDV983X4XQVV4F2G",
  "page": 1,
  "ordersPerPage": 2,
  "sort": {
    "created_at": "ASC"
  },
  "filter": {
    "status": {
      "in": [
        "pending",
        "completed"
      ]
    },
    "fulfillment_status": {
      "eq": "not_fulfilled"
    },
    "payment_status": {
      "eq": "awaiting"
    },
    "created_at": {
      "gte": "2024-11-01T00:00:00Z",
      "lte": "2024-11-30T23:59:59Z"
    }
  }

}

### Get Seller Order Details
GET http://localhost:9000/seller/order/detail?order_id=order_01JEQHZ1Z8SKW7V5732HQSYD7R
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

### MODIFY ORDER STATUS && ADD NOTE?
PUT http://localhost:9000/seller/order/status
Content-Type: application/json

{
  "order_id": "order_01JEQHZ1Z8SKW7V5732HQSYD7R",
  "status": "cancelled",
  "note": "this guy just wasted our time, just return his money so he shuts up"

}

### Store Name
GET  http://localhost:9000/seller/store/name
Content-Type: application/json

{
  "wallet_address": "0xfb20a78fd35d20925af6f7379ab35fa6c41e9834"
}
