// POST auth
POST http://localhost:9000/seller/auth

### Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json

{
    "store_id": "store_01JCK8MX8DZCHXDMMR8SNKN7E3",
    "wallet_address": "0x4fBCF49cC0f91d66Bc5bBbE931913D8709592012"
}

###
// Get Seller Orders
POST http://localhost:9000/seller/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

{
    "store_id": "store_01JDH8E3NH8WS1YTXZW10WCQV6",
    "page": 1,
    "ordersPerPage": 4,
     "sort": {
    "field": "created_at",
    "direction": "ASC"
  },
    "filter": {"status": {"eq": "pending"}}
}

### Get Seller Order Details
GET http://localhost:9000/seller/order/detail?order_id=order_01JD7D8YKNMK7YD1PTP2RARYVB
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUpDSFo5Uks3WktEMk42MzVWWjZTWUFDRiIsImRvbWFpbiI6InN0b3JlIiwiaWF0IjoxNzMyMTEyNzU2LCJleHAiOjE3MzQ3MDQ3NTZ9.y5nV3A0w1H1q5GVVYZnJWzGPaODiurCGjpUhdWFmhgM

### MODIFY ORDER STATUS && ADD NOTE?
PUT http://localhost:9000/seller/order/status
Content-Type: application/json

{
  "order_id": "order_01JCHZ33D14HBQ298MAQ6JC1D2",
  "status": "canceled",
  "note": "this guy just wasted our time, just return his money so he shuts up"

}

